export const images = {
  hero: "/images/prasanna-hero-new-soft.png",
  about: "/images/about-prasanna-fc95d7.png",
  avatar: "/images/logo.png?v=green",
  video: "/images/video-thumbnail.png",
  stage: [
    "/images/stage-1-6cc4de.png",
    "/images/stage-2-5ff18.png",
    "/images/stage-3-5ff18.png",
    "/images/stage-4-6cc4de.png",
  ],
  headshots: [
    "/images/headshot-1-6790a1.png",
    "/images/headshot-2-674c5b.png",
    "/images/headshot-3-674c5b.png",
    "/images/headshot-4-674c5b.png",
    "/images/headshot-5-674c5b.png",
    "/images/headshot-6-674c5b.png",
    "/images/headshot-7-674c5b.png",
  ],
  logos: {
    nasSummit: "/images/logo-nas-summit-56586a.png",
    successResources: "/images/logo-success-resources-4b6f42.png",
    nasDaily: "/images/logo-nas-daily-51178b.png",
    intel: "/images/logo-intel-56586a.png",
    deutscheWelle: "/images/logo-deutsche-welle-56586a.png",
    propellus: "/images/logo-propellus-56586a.png",
    lscs: "/images/logo-lscs-56586a.png",
  },
  testimonials: {
    bernadette: "/images/testimonial-bernadette-56586a.png",
    priyanka: "/images/testimonial-priyanka-56586a.png",
    dasha: "/images/testimonial-dasha-56586a.png",
    liana: "/images/testimonial-liana-56586a.png",
    marius: "/images/testimonial-marius-56586a.png",
    karthikeyan: "/images/testimonial-karthikeyan-56586a.png",
    subra: "/images/testimonial-subra-56586a.png",
    luis: "/images/testimonial-luis-56586a.png",
  },
} as const;
